import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import Nav from "@/app/components/nav";
import Fotter from "@/app/components/footer";
import "./styles/globals.css";

const notoSerif = Noto_Serif({
  weight:["300",],
  style:["italic","normal"],
  subsets:["latin"]
    })

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={notoSerif.className}>
        <Nav></Nav>
        {children}
        <Fotter></Fotter>
      </body>
    </html>
  );
}
