import type { Metadata } from "next";
import Nav from '@/app/components/nav'
import Fotter from '@/app/components/footer'
import "./styles/globals.css";


export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
         <Nav></Nav>
        {children}
        <Fotter></Fotter>
      </body>
    </html>
  );
}
