export const Products = [
  {
    titleKey: "products.1.title",
    descriptionKey: "products.1.description",
    id: 1,
    price: 400,
    image: "/ropa/1.webp",
    imageHover: "/ropa/1-2.webp",
    category: "CAMISA",
    },
  {
    titleKey: "products.2.title",
    descriptionKey: "products.2.description",
    id: 2,
    category: "ABRIGO",
    price: 350,
    image: "/ropa/2.webp",
    imageHover: "/ropa/2-2.webp",
   },
  {
    titleKey: "products.3.title",
    descriptionKey: "products.3.description",
    id: 3,
    category: "ABRIGO",
    price: 750,
    image: "/ropa/3.webp",
    imageHover: "/ropa/3-2.webp",
   },
  {
    titleKey: "products.4.title",
    descriptionKey: "products.4.description",
    id: 4,
    category: "CAMISA",
    price: 400,
    image: "/ropa/4.webp",
    imageHover: "/ropa/4-2.webp",
   },

  {
    titleKey: "products.5.title",
    descriptionKey: "products.5.description",
    id: 5,
    category: "CAMISA",
    price: 200,
    image: "/ropa/5.webp",
    imageHover: "/ropa/5-2.webp",
},
  {
    titleKey: "products.6.title",
    descriptionKey: "products.6.description",
    id: 6,
    category: "PANTALON ",
    price: 240,
    image: "/ropa/6.webp",
    imageHover: "/ropa/6-2.webp",
  },
  {
    titleKey: "products.7.title",
    descriptionKey: "products.7.description",
    id: 7,
    category: "CAMISA",
    price: 240,
    image: "/ropa/7.webp",
    imageHover: "/ropa/7-2.avif",
  },
  {
    titleKey: "products.8.title",
    descriptionKey: "products.8.description",
    category: "SUETER",
    id: 8,
    price: 240,
    image: "/ropa/8.webp",
    imageHover: "/ropa/8-2.avif",
  },
  {
    titleKey: "products.9.title",
    descriptionKey: "products.9.description",
    category: "SUETER",
    id: 9,
    price: 340,
    image: "/ropa/9.webp",
    imageHover: "/ropa/9-2.avif",
  },
  {
    titleKey: "products.10.title",
    descriptionKey: "products.10.description",
    category: "SUETER",
    id: 10,
    price: 290,
    image: "/ropa/10.webp",
    imageHover: "/ropa/10-2.avif",
  },
  {
    titleKey: "products.11.title",
    descriptionKey: "products.11.description",
    category: "PANTALON",
    id: 11,
    price: 290,
    image: "/ropa/11.webp",
    imageHover: "/ropa/11-2.avif",
  },
  {
    titleKey: "products.12.title",
    descriptionKey: "products.12.description",
    category: "SUETER",
    id: 12,
    price: 200,
    image: "/ropa/12.webp",
    imageHover: "/ropa/12-2.avif",
  },
  {
    titleKey: "products.13.title",
    descriptionKey: "products.13.description",
    category: "ABRIGO",
    id: 13,
    price: 200,
    image: "/ropa/13.webp",
    imageHover: "/ropa/13-2.avif",
  },
  {
    titleKey: "products.14.title",
    descriptionKey: "products.14.description",
    category: "ABRIGO",
    id: 14,
    price: 350,
    image: "/ropa/14.webp",
    imageHover: "/ropa/14-2.webp",
  },
  {
    titleKey: "products.15.title",
    descriptionKey: "products.15.description",
    category: "ABRIGO",
    id: 15,
    price: 800,
    image: "/ropa/15.webp",
    imageHover: "/ropa/15-2.avif",
  },
  {
    titleKey: "products.16.title",
    descriptionKey: "products.16.description",
    category: "CAMISA",
    id: 16,
    price: 200,
    image: "/ropa/16.webp",
    imageHover: "/ropa/16-2.avif",
  },
  {
    titleKey: "products.17.title",
    descriptionKey: "products.17.description",
    category: "CAMISA",
    id: 17,
    price: 420,
    image: "/ropa/17.webp",
    imageHover: "/ropa/17-2.avif",
  },
  {
    titleKey: "products.18.title",
    descriptionKey: "products.18.description",
    category: "BOINA",
    id: 18,
    price: 80,
    image: "/ropa/18.webp",
    imageHover: "/ropa/18-2.webp",
  },
  {
    titleKey: "products.19.title",
    descriptionKey: "products.19.description",
    category: "ZAPATOS",
    id: 19,
    price: 520,
    image: "/ropa/19.webp",
    imageHover: "/ropa/19-2.webp",
  },
  {
    titleKey: "products.20.title",
    descriptionKey: "products.20.description",
    category: "ZAPATOS",
    id: 20,
    price: 370,
    image: "/ropa/20.webp",
    imageHover: "/ropa/20-2.webp",
  },
  {
    titleKey: "products.21.title",
    descriptionKey: "products.21.description",
    id: 21,
    category: "ABRIGO",
    price: 995,
    image: "/ropa/21.webp",
    imageHover: "/ropa/21-2.webp",
  },
];
